# Generated by Django 5.2.4 on 2025-07-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
